In [1]:
import tensorflow as tf
print(tf.__version__)

2.10.1


In [2]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
### Vocabulary size
voc_size=500

One Hot Representation

In [6]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

## returns the index where the value is 1 and hence represents the word
# [ 0
#   0
#   0
#   1
#   .
#   . ] => 500 dimension

[[269, 138, 271, 40], [269, 138, 271, 279], [269, 60, 271, 433], [167, 270, 153, 266, 11], [167, 270, 153, 266, 85], [293, 269, 491, 271, 456], [323, 359, 111, 266]]


Word Embedding Represntation

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

sentences are not of the same size hence we need padding to make all sentences of same length

In [9]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 269 138 271  40]
 [  0   0   0   0 269 138 271 279]
 [  0   0   0   0 269  60 271 433]
 [  0   0   0 167 270 153 266  11]
 [  0   0   0 167 270 153 266  85]
 [  0   0   0 293 269 491 271 456]
 [  0   0   0   0 323 359 111 266]]


In [10]:
## 10 feature dimensions
dim=10
## each value is represented in form a vector containing 10 values

In [11]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________


In [13]:
## 'the glass of milk'
embedded_docs[0]

array([  0,   0,   0,   0, 269, 138, 271,  40])

In [14]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 260ms/step


array([[ 0.02889477, -0.02189219,  0.04914543,  0.03144081,  0.02037458,
         0.01159503, -0.02062805,  0.03657762, -0.00136096, -0.02000031],
       [ 0.02889477, -0.02189219,  0.04914543,  0.03144081,  0.02037458,
         0.01159503, -0.02062805,  0.03657762, -0.00136096, -0.02000031],
       [ 0.02889477, -0.02189219,  0.04914543,  0.03144081,  0.02037458,
         0.01159503, -0.02062805,  0.03657762, -0.00136096, -0.02000031],
       [ 0.02889477, -0.02189219,  0.04914543,  0.03144081,  0.02037458,
         0.01159503, -0.02062805,  0.03657762, -0.00136096, -0.02000031],
       [-0.04564426,  0.0426149 , -0.04440235, -0.01031623, -0.00011925,
        -0.01136029, -0.04035568, -0.01807887,  0.03803784,  0.02586663],
       [ 0.03351733,  0.04941558, -0.04300826,  0.01656364,  0.00144827,
        -0.03277974,  0.01945365, -0.04909389,  0.04536363,  0.03777554],
       [ 0.00912696, -0.02804581,  0.02629225,  0.01498381,  0.02048296,
         0.04210765,  0.04239017,  0.02669555

In [15]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 100ms/step
[[[ 0.02889477 -0.02189219  0.04914543  0.03144081  0.02037458
    0.01159503 -0.02062805  0.03657762 -0.00136096 -0.02000031]
  [ 0.02889477 -0.02189219  0.04914543  0.03144081  0.02037458
    0.01159503 -0.02062805  0.03657762 -0.00136096 -0.02000031]
  [ 0.02889477 -0.02189219  0.04914543  0.03144081  0.02037458
    0.01159503 -0.02062805  0.03657762 -0.00136096 -0.02000031]
  [ 0.02889477 -0.02189219  0.04914543  0.03144081  0.02037458
    0.01159503 -0.02062805  0.03657762 -0.00136096 -0.02000031]
  [-0.04564426  0.0426149  -0.04440235 -0.01031623 -0.00011925
   -0.01136029 -0.04035568 -0.01807887  0.03803784  0.02586663]
  [ 0.03351733  0.04941558 -0.04300826  0.01656364  0.00144827
   -0.03277974  0.01945365 -0.04909389  0.04536363  0.03777554]
  [ 0.00912696 -0.02804581  0.02629225  0.01498381  0.02048296
    0.04210765  0.04239017  0.02669555 -0.04719058  0.03344823]
  [ 0.00304021  0.02205152  0.04877944 -0.0208207   0.0376

In [16]:
embedded_docs[0]

array([  0,   0,   0,   0, 269, 138, 271,  40])

In [17]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 15ms/step
[[ 0.02889477 -0.02189219  0.04914543  0.03144081  0.02037458  0.01159503
  -0.02062805  0.03657762 -0.00136096 -0.02000031]
 [ 0.02889477 -0.02189219  0.04914543  0.03144081  0.02037458  0.01159503
  -0.02062805  0.03657762 -0.00136096 -0.02000031]
 [ 0.02889477 -0.02189219  0.04914543  0.03144081  0.02037458  0.01159503
  -0.02062805  0.03657762 -0.00136096 -0.02000031]
 [ 0.02889477 -0.02189219  0.04914543  0.03144081  0.02037458  0.01159503
  -0.02062805  0.03657762 -0.00136096 -0.02000031]
 [-0.04564426  0.0426149  -0.04440235 -0.01031623 -0.00011925 -0.01136029
  -0.04035568 -0.01807887  0.03803784  0.02586663]
 [ 0.03351733  0.04941558 -0.04300826  0.01656364  0.00144827 -0.03277974
   0.01945365 -0.04909389  0.04536363  0.03777554]
 [ 0.00912696 -0.02804581  0.02629225  0.01498381  0.02048296  0.04210765
   0.04239017  0.02669555 -0.04719058  0.03344823]
 [ 0.00304021  0.02205152  0.04877944 -0.0208207   0.03763834  0.02858472